export const resolveData = (data, path) => {
  if (!data || !path) return "";
  return path.split(".").reduce((acc, field) => {
    if (Array.isArray(acc)) {
      acc = acc[0];
    }
    return acc ? acc[field] : null;
  }, data);
};

export const TableSchemas = {
  users: [
    { header: "User", field: "first_name" },
    { header: "Last Name", field: "last_name" },
    { header: "Email", field: "email" },
    { header: "Role", field: "role" },
    { header: "Team", field: "teams.name" },
    { header: "Status", field: "status" },
    { header: "Created At", field: "created_at", type: "date" },
    { header: "Action", field: "action" },
  ],

  dashboard: [
    { header: "Request ID", field: "requestID" },
    { header: "Type", field: "type" },
    { header: "Requestor", field: "requestor" },
    { header: "Status", field: "status" },
    { header: "Date", field: "Date", type: "date" },
  ],

  workflows: [
    { header: "Sr.NO", field: "srno" },
    { header: "Workflow ID", field: "workflow_id_str" },
    { header: "Workflow Name", field: "name" },
    { header: "Trigger", field: "trigger" },
    { header: "Owner", field: "owner_name" },
    { header: "Version", field: "versions.version" },
    { header: "Status", field: "status" },
    { header: "Created At", field: "created_at", type: "date" },
    { header: "Updated At", field: "updated_at", type: "date" },
    { header: "Action", field: "action" },
  ],

  execution: [
    { header: "Sr.NO", field: "srno" },
    { header: "Execution ID", field: "execution_id_str" },
    { header: "Workflow ID", field: "workflow_id_str" },
    { header: "Status ", field: "status" },
    { header: "started_at", field: "started_at", type: "date" },
    { header: "finished_at", field: "finished_at", type: "date" },
    { header: "Triggered By", field: "triggered_by" },
    { header: "Action", field: "action" },
  ],

  task: [
    { header: "Sr.NO", field: "srno" },
    { header: "Task ID", field: "task_key" },
    { header: "Task Name", field: "name" },
    { header: "Status", field: "status" },
    { header: "Assigned To", field: "assignee_role" },
    { header: "Priority", field: "priority" },
    { header: "Created At", field: "created_at", type: "date" },
    { header: "Updated At", field: "updated_at", type: "date" },
    { header: "Due At", field: "due_at", type: "date" },
    { header: "Action", field: "action" },
  ],

  approval: [
    { header: "Sr.No", field: "srno" },
    { header: "Approval ID", field: "approval_key" },
    { header: "Stage", field: "stage" },
    { header: "Requester Name", field: "requester_name" },
    { header: "Priority", field: "priority" },
    { header: "Status", field: "status" },
    { header: "SLA Hours", field: "sla_hours" },
    { header: "Created At", field: "created_at", type: "date" },
    // { header: "Action", field: "action" },
  ],
  versions: [
    { header: "Sr.No", field: "srno" },
    { header: "Version", field: "version" },
    { header: "Version ID", field: "version_key" },
    { header: "Workflow ID", field: "workflow_id_str" },
    { header: "Status", field: "status" },
    { header: "Created By", field: "created_by" },
    { header: "Created At", field: "created_at", type: "date" },
    { header: "Is Active", field: "is_active", type: "boolean" },
    { header: "Action", field: "action" },
  ],

  team: [
    { header: "Sr.No", field: "srno" },
    { header: "Team Name", field: "name" },
    // { header: "Lead", field: "lead_id" },
    { header: "User", field: "users.first_name" },
    { header: "Description", field: "description" },
    { header: "Status", field: "status" },
    { header: "Is Active", field: "is_active", type: "boolean" },
    { header: "Created At", field: "created_at", type: "date" },
    { header: "Action", field: "action" },
  ],
  auditLogsUser: [
    { header: "Sr.No", field: "srno" },
    { header: "Name", field: "user_display_name" },
    { header: "Role", field: "role" },
    { header: "Department", field: "dept" },
    { header: "IP Address", field: "ip_address" },
    { header: "Action", field: "action_type" },
    { header: "Resource", field: "resource" },
    { header: "Status", field: "status" },
    { header: "Created At", field: "created_at", type: "date" },
    // { header: "Action", field: "action" },
  ],
  auditLogsAdmin: [
    { header: "Sr.No", field: "srno" },
    { header: "Name", field: "user_display_name" },
    { header: "Role", field: "role" },
    { header: "Department", field: "dept" },
    { header: "IP Address", field: "ip_address" },
    { header: "Action", field: "action_type" },
    { header: "Resource", field: "resource" },
    { header: "Created At", field: "created_at", type: "date" },
    { header: "Status", field: "status" },
    // { header: "Action", field: "action" },
  ],

  auditLogsSystem: [
    { header: "Sr.No", field: "srno" },
    { header: "Name", field: "user_display_name" },
    { header: "service", field: "service" },
    { header: "event", field: "event" },
    { header: "severity", field: "severity" },
    { header: "Resource", field: "resource" },
    { header: "Created At", field: "created_at", type: "date" },
    { header: "Status", field: "status" },
    { header: "Action Type", field: "action_type" },
    // { header: "Action", field: "action" },
  ],
  policies: [
    { header: "Sr.No", field: "srno" },
    { header: "Name", field: "name" },
    { header: "policy_code", field: "policy_code" },
    { header: "regulation_type", field: "regulation_type" },
    { header: "risk_level", field: "risk_level" },
    { header: "effective_from", field: "effective_from" },
    { header: "review_frequency", field: "review_frequency" },
    { header: "Created At", field: "created_at", type: "date" },
    { header: "Status", field: "status" },
    { header: "Action", field: "approval" },
    { header: "Action", field: "action" },
  ],

  evidence: [
    { header: "Sr.No", field: "srno" },
    { header: "evidence_name", field: "evidence_name" },
    { header: "control_id", field: "control_id" },
    { header: "collection_date", field: "collection_date", type: "date" },
    { header: "description", field: "description" },
    { header: "Created At", field: "created_at", type: "date" },
    { header: "Download", field: "file_path" },
    { header: "Status", field: "status" },
    { header: "Approval Action", field: "approval" },
    { header: "Action", field: "action" },
  ],
  risks: [
    { header: "Sr.No", field: "srno" },
    { header: "risk_code", field: "risk_code" },
    { header: "category", field: "category" },
    { header: "risk_title", field: "risk_title" },
    { header: "description", field: "description" },
    { header: "impact", field: "impact" },
    { header: "mitigation_plan", field: "mitigation_plan" },
    { header: "identified_at", field: "identified_at", type: "date" },
    // { header: "resolved_at", field: "resolved_at", type: "date" },
    { header: "Status", field: "status" },
    { header: "Approval Action", field: "approval" },
    { header: "Action", field: "action" },
  ],

  invoices: [
    { header: "Sr.No", field: "srno" },
    { header: "invoice_number", field: "invoice_number" },
    { header: "Amount", field: "amount" },
    { header: "Date", field: "created_at" },
    { header: "Status", field: "status" },
    { header: "Action", field: "file" },
  ],
};
