import React from "react";
import {
  CheckCircle2,
  ChevronDown,
  ExternalLink,
  MoreHorizontal,
  Zap,
  Search,
  Settings,
  Bell,
  ArrowUpRight,
  ArrowDownRight,
  ShieldCheck,
  Filter,
  Eye,
  Link,
  Bolt,
  ChevronRight,
} from "lucide-react";
import { NavLink, useNavigate, useParams } from "react-router-dom";

const WorkflowApprovals = () => {
  const navigate = useNavigate();
  const { workflowId } = useParams();

  const handleRowClick = (approvalId) => {
    navigate(`${approvalId}?workflowId=${workflowId}`);
  };

  const approvals = [
    {
      id: "APP-9021-X",
      type: "Budget Expansion",
      dept: "Q3 Marketing Dept",
      requester: {
        name: "Alex Rivera",
        img: "https://lh3.googleusercontent.com/aida-public/AB6AXuByF5nVZZIq0yKnZj9tuldcuZsikGFvGxIWjlwpLwWud6bxYLr2N3xoTYjfYbI13I-00AAyRfnuMSZgh457iNFjBUuBOt5voNnUWiSF5JIoRqU4sMvmINKqzRxep8DKer6g7YS6aY3f2GAHswse5nO6VHjfHWfD1aMyx5qgxe1MzhyDJ0plRKGO1zsxzai1rX5Eh86NBbt7gMwQ5Y0HcBwfgeKZ36RTypWFLr2waZLzUuUj5JwhgfLAAXUJ0pS0W81Sf8fOQQ6OMBg",
      },
      approver: {
        name: "Marcus Chen",
        img: "https://lh3.googleusercontent.com/aida-public/AB6AXuBoybTxWG70LEfzYfWhxUSw6yaVUbpXy0OFq3WN3VFZ788fYtEJrUK2ZVyLaLQmNDZ8KwyQF0NGljrd_NDsJkQMy71YQ09PCh-vWAU8JZskz5bDdT0FwcV_3KfFdTqZwusHSYdudGb6v_2k4aSBunKSyQZjUcI-XFw6uGMQzT3pX22Xp1mjc_MXEZOpixgy2QEauL_EYvOrRXXvT-JMybec6RhClXOtLqv7Vk7tktUMOPAZ_xnFkfirWPCB2-GirzYBgtJG7sUBW3Q",
      },
      status: "Pending",
      stage: "Finance Review",
      sla: 75,
      timeText: "18h / 24h",
      lastAction: "2h ago by System",
      statusStyles: "bg-blue-500/10 text-blue-600 dark:text-blue-400",
    },
    {
      id: "APP-9055-Z",
      type: "New Hire Access",
      dept: "Engineering - Senior L6",
      requester: {
        name: "Sarah Jenkins",
        img: "https://lh3.googleusercontent.com/aida-public/AB6AXuB-JEhL_Fl83PKv_-wFtWGxLKZNFbPMgDum_cJsFxILYvKN1CHe7T254wVz467SrxsrA1A6sQZbXmYfsVNyKJe_dp9i4MljGzYy1nvEFudK7wFuGXj8U7tS3Qr99yqHpps9MBVUZ28Ly-qGiazx9G_I4T7U2fFQX40_672aUGpW6652zq92qCQrWsM4HPlEH-juJXXIxRQGpP2Q9ESivpTWCxMkI9zPoAni-OtManbkgq7gP5Sd_2_bnbCmfM1bbrgkbEYHylzhKNM",
      },
      approver: {
        name: "Linda Wu",
        img: "https://lh3.googleusercontent.com/aida-public/AB6AXuCFUSkuBdMU6wScsjrJ7Rm9dUw-eJoQY1Y1QO_adW9V71Bx-AKfVOLqCRLBkpYUKe_CHPqmxLkh7nS8qouJoVJrNQi6QT6Xg86dSwMFXp7iCerhvKFpTZSQ3LgbmLhRJp-nZ5X0pFGkqgQGYHT9JmnbYudMsWQJ0jLQIoPB3aHpDa3IJWmANQokhSv6pEE6qNw06-7ciZA7F8BAsUclJxRAehKJOkR9CIHtPBMmnvDLOvXUUX3SR3oq2nylhJIxW9bWmMnhAARTUv0",
      },
      status: "Escalated",
      stage: "Security Provisioning",
      sla: 100,
      timeText: "32h / 24h",
      lastAction: "8h ago by Auto-Bot",
      statusStyles: "bg-amber-500/10 text-amber-500",
      slaCritical: true,
    },
    {
      id: "APP-8992-B",
      type: "Policy Exception",
      dept: "Travel & Expenses",
      requester: {
        name: "David G.",
        img: "https://lh3.googleusercontent.com/aida-public/AB6AXuD7N4IGxGpzdXnEbQxgv07BDTYalFrvaGsCldFbTNYuhfmbFxs-eHw7hyN8VXNbR1UKN04qTnoOJHt2epIFhCi3yETq82LBnLACX4zTe5f_JaawDvAOzjCMIn7t5f9qNLdjVtFVgFEWjNiFmgHwZ9Ieqd6VUMwNtqu-P-Tc8TrEqSob4GcdaRKmqm1TZDggcv8hKX9Aaey19bDT7g2UFjrkd7EeB4zHZeIV4RSiP1mSGTjIDewQZFWDa0reaThfklZLzQDxu-fg2QY",
      },
      approver: null,
      status: "Approved",
      stage: "Archived",
      sla: 15,
      timeText: "4h / 24h",
      lastAction: "1d ago by Marcus Chen",
      statusStyles: "bg-emerald-500/10 text-emerald-600",
    },
  ];

  return (
    <div className="flex-1 space-y-6 p-10 bg-[#f6f6f8] dark:bg-[#101622] min-h-screen font-sans">
      {/* Page Heading */}
      <nav className="flex items-center gap-2 mb-6 text-sm font-medium text-slate-500">
        <NavLink
          to="/workflows"
          className="hover:text-blue-600 transition-colors"
        >
          Workflows
        </NavLink>
        <ChevronRight size={14} />
        <span className="text-slate-900 dark:text-white">{workflowId}</span>
        <ChevronRight size={14} />
        <span className="text-slate-900 dark:text-white">Approvals</span>
      </nav>
      <div className="flex flex-wrap justify-between items-end gap-3">
        <div className="flex flex-col gap-1">
          <h1 className="text-slate-900 dark:text-white text-3xl font-black leading-tight tracking-tight">
            Approvals
          </h1>
          <p className="text-slate-500 dark:text-slate-400 text-sm font-normal">
            Monitoring and governance of approvals generated by Enterprise
            Workflow #{workflowId || "882"}
          </p>
        </div>
        <div className="flex gap-3">
          <button className="flex items-center justify-center rounded-lg h-10 px-4 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-white text-sm font-bold hover:bg-slate-50 transition-colors">
            <ShieldCheck size={18} className="mr-2" />
            <span>View Approval Rules</span>
          </button>
          <button className="flex items-center justify-center rounded-lg h-10 px-4 bg-[#0f49bd] text-white text-sm font-bold hover:bg-blue-700 transition-colors shadow-lg shadow-blue-900/20">
            <Zap size={18} className="mr-2" />
            <span>Escalation Settings</span>
          </button>
        </div>
      </div>

      {/* KPI Section */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <KPICard
          label="Pending"
          value="142"
          trend="+12.5%"
          status="In Review"
          color="primary"
          isUp
        />
        <KPICard
          label="Approved"
          value="894"
          trend="-5.2%"
          status="Finalized"
          color="emerald"
          isUp={false}
        />
        <KPICard
          label="Rejected"
          value="23"
          trend="+2.1%"
          status="Terminated"
          color="rose"
          isUp
        />
        <KPICard
          label="Avg Approval Time"
          value="1.4 Days"
          trend="-10%"
          status="SLA Metric"
          color="amber"
          isUp={false}
        />
      </div>

      {/* Filter Bar */}
      <div className="flex flex-wrap items-center gap-3 py-2 border-y border-slate-200 dark:border-slate-800">
        <span className="text-xs font-bold uppercase text-slate-500 tracking-wider mr-2">
          Filters:
        </span>
        {[
          "Status: All",
          "Approver: All",
          "Stage: All",
          "Range: Last 30 Days",
        ].map((filter) => (
          <button
            key={filter}
            className="flex h-9 items-center gap-x-2 rounded-lg bg-white dark:bg-slate-800 px-3 border border-slate-200 dark:border-slate-700 hover:bg-slate-50 text-xs font-semibold text-slate-700 dark:text-slate-200"
          >
            {filter}
            <ChevronDown size={14} className="opacity-50" />
          </button>
        ))}
        <div className="flex-1" />
        <button className="text-xs text-slate-500 hover:text-[#0f49bd] underline font-medium">
          Clear all filters
        </button>
      </div>

      {/* Main Table */}
      <div className="bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 overflow-hidden shadow-sm">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-slate-50 dark:bg-slate-800/50 text-slate-500 dark:text-slate-400 text-[11px] font-bold uppercase tracking-wider">
                <th className="px-6 py-4 border-b border-slate-200 dark:border-slate-800">
                  Approval ID
                </th>
                <th className="px-6 py-4 border-b border-slate-200 dark:border-slate-800">
                  Request Type
                </th>
                <th className="px-6 py-4 border-b border-slate-200 dark:border-slate-800">
                  Requested By
                </th>
                <th className="px-6 py-4 border-b border-slate-200 dark:border-slate-800">
                  Current Approver
                </th>
                <th className="px-6 py-4 border-b border-slate-200 dark:border-slate-800">
                  Status
                </th>
                <th className="px-6 py-4 border-b border-slate-200 dark:border-slate-800">
                  Stage
                </th>
                <th className="px-6 py-4 border-b border-slate-200 dark:border-slate-800 w-32">
                  SLA Progress
                </th>
                <th className="px-6 py-4 border-b border-slate-200 dark:border-slate-800 text-right">
                  Actions
                </th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
              {approvals.map((item) => (
                <tr
                  key={item.id}
                  className="hover:bg-slate-50 dark:hover:bg-slate-800/30 transition-colors group cursor-pointer"
                  onClick={() => handleRowClick(item.id)}
                >
                  <td className="px-6 py-4 font-mono text-xs text-[#0f49bd] dark:text-blue-400 font-medium">
                    {item.id}
                  </td>
                  <td className="px-6 py-4">
                    <p className="text-sm font-semibold text-slate-900 dark:text-white">
                      {item.type}
                    </p>
                    <p className="text-[11px] text-slate-500">{item.dept}</p>
                  </td>
                  <td className="px-6 py-4">
                    <UserCell
                      name={item.requester.name}
                      img={item.requester.img}
                    />
                  </td>
                  <td className="px-6 py-4">
                    {item.approver ? (
                      <UserCell
                        name={item.approver.name}
                        img={item.approver.img}
                      />
                    ) : (
                      <div className="flex items-center gap-2 text-slate-400">
                        <CheckCircle2 size={14} className="text-emerald-500" />
                        <span className="text-xs">Complete</span>
                      </div>
                    )}
                  </td>
                  <td className="px-6 py-4">
                    <span
                      className={`inline-flex items-center px-2 py-0.5 rounded text-[11px] font-bold uppercase ${item.statusStyles}`}
                    >
                      {item.status}
                    </span>
                  </td>
                  <td className="px-6 py-4 text-xs text-slate-600 dark:text-slate-400">
                    {item.stage}
                  </td>
                  <td className="px-6 py-4">
                    <div className="flex flex-col gap-1.5 w-full">
                      <div className="flex justify-between text-[10px] font-bold">
                        <span
                          className={
                            item.slaCritical
                              ? "text-rose-500"
                              : "text-slate-900 dark:text-white"
                          }
                        >
                          {item.timeText.split(" / ")[0]}
                        </span>
                        <span className="text-slate-400">
                          / {item.timeText.split(" / ")[1]}
                        </span>
                      </div>
                      <div className="h-1 w-full bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden">
                        <div
                          className={`h-full rounded-full ${item.slaCritical ? "bg-rose-500" : "bg-[#0f49bd]"}`}
                          style={{ width: `${item.sla}%` }}
                        ></div>
                      </div>
                    </div>
                  </td>
                  <td
                    className="px-6 py-4 text-right"
                    onClick={(e) => e.stopPropagation()}
                  >
                    <div className="flex justify-end gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                      <ActionBtn icon={<Eye size={16} />} title="View" />
                      <ActionBtn icon={<Link size={16} />} title="Link" />
                      <ActionBtn
                        icon={<Bolt size={16} />}
                        title="Escalate"
                        color="rose"
                      />
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <div className="px-6 py-4 bg-slate-50 dark:bg-slate-800/50 border-t border-slate-200 dark:border-slate-800 flex items-center justify-between">
          <p className="text-xs text-slate-500 font-medium">
            Showing 1 to 3 of 142 entries
          </p>
          <div className="flex gap-2">
            <button className="rounded bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 h-8 px-3 text-[11px] font-bold text-slate-400 cursor-not-allowed">
              Previous
            </button>
            <button className="rounded bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 h-8 px-3 text-[11px] font-bold text-slate-600 dark:text-white hover:bg-slate-50">
              Next
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

/* --- Sub-Components for Cleanliness --- */

const KPICard = ({ label, value, trend, status, color, isUp }) => {
  const colorMap = {
    primary: "bg-blue-500/10 text-blue-600",
    emerald: "bg-emerald-500/10 text-emerald-600",
    rose: "bg-rose-500/10 text-rose-500",
    amber: "bg-amber-500/10 text-amber-500",
  };

  return (
    <div className="flex flex-col gap-2 rounded-xl p-6 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm">
      <div className="flex justify-between items-start">
        <p className="text-slate-500 dark:text-slate-400 text-sm font-medium">
          {label}
        </p>
        <span
          className={`${colorMap[color]} text-[10px] font-bold px-2 py-0.5 rounded-full uppercase`}
        >
          {status}
        </span>
      </div>
      <p className="text-slate-900 dark:text-white text-3xl font-bold tracking-tight">
        {value}
      </p>
      <div
        className={`flex items-center gap-1 text-sm font-medium ${isUp ? "text-emerald-500" : "text-rose-500"}`}
      >
        {isUp ? <ArrowUpRight size={14} /> : <ArrowDownRight size={14} />}
        <span>{trend} vs last month</span>
      </div>
    </div>
  );
};

const UserCell = ({ name, img }) => (
  <div className="flex items-center gap-2">
    <div className="w-6 h-6 rounded-full bg-slate-200 dark:bg-slate-700 overflow-hidden">
      <img src={img} alt={name} className="w-full h-full object-cover" />
    </div>
    <span className="text-sm text-slate-700 dark:text-slate-300 whitespace-nowrap">
      {name}
    </span>
  </div>
);

const ActionBtn = ({ icon, title, color = "slate" }) => (
  <button
    className={`p-1.5 rounded transition-colors ${
      color === "rose"
        ? "hover:bg-rose-100 dark:hover:bg-rose-900/30 text-slate-400 hover:text-rose-600"
        : "hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-400 hover:text-[#0f49bd]"
    }`}
    title={title}
  >
    {icon}
  </button>
);

export default WorkflowApprovals;
