import {
  ArrowDownRight,
  ArrowUpRight,
  ChevronDown,
  ChevronRight,
  Search,
  ShieldCheck,
  X,
  Zap,
} from "lucide-react";
import { Menu } from "primereact/menu";
import { useEffect, useRef, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { NavLink, useNavigate, useParams } from "react-router-dom";
import DynamicTable from "../../Components/DynamicTable";
import FilterButton from "../../Components/MiniComponent/FilterButton";
import Paginator from "../../Components/Paginator";
import { TableSchemas } from "../../Utils/TableSchemas";
import { get_Workflow_Approvals } from "../../RTKThunk/WorkflowThunk";
const WorkflowApprovals = () => {
  const navigate = useNavigate();
  const { workflowId } = useParams();
  const dispatch = useDispatch();
  const menuStatus = useRef(null);
  const menuPriority = useRef(null);
  const [filters, setFilters] = useState({
    status: "All",
    priority: "All",
  });
  const [page, setPage] = useState(1);
  const rows = 10;
  const [search, setSearch] = useState("");
  const [debouncedSearch, setDebouncedSearch] = useState("");
  const { loading, currentWorkflowApprovals, total } = useSelector(
    (state) => state.workflows,
  );
  useEffect(() => {
    dispatch(
      get_Workflow_Approvals({
        workflowId,
        page,
        limit: rows,
        status: filters.status === "All" ? null : filters.status,
        priority: filters.priority === "All" ? null : filters.priority,
        search: debouncedSearch,
      }),
    );
  }, [
    dispatch,
    workflowId,
    page,
    filters.status,
    filters.priority,
    debouncedSearch,
  ]);

  const approvalData = currentWorkflowApprovals || [];

  const handleRowClick = (approvalId) => {
    const id = approvalId.data.approval_key || " ";
    if (id) {
      navigate(`/workflows/${workflowId}/approvals/${id}`);
    }
  };

  const onPageChange = (selectedPage) => {
    setPage(selectedPage + 1);
  };

  const statusItems = [
    {
      label: "All",
      className: filters.status === "All" ? "font-bold text-blue-600" : "",
      command: () => setFilters((prev) => ({ ...prev, status: "All" })),
    },
    {
      label: "Escalated",
      command: () => setFilters((prev) => ({ ...prev, status: "ESCALATED" })),
    },
    {
      label: "Pending",
      command: () => setFilters((prev) => ({ ...prev, status: "PENDING" })),
    },
  ];

  const priorityItems = [
    {
      label: "All Priority",
      command: () => setFilters((f) => ({ ...f, priority: "All" })),
    },
    {
      label: "High (8-10)",
      template: (item) => (
        <div className="flex items-center gap-2 p-2 text-red-600 font-bold">
          <div className="size-2 rounded-full bg-red-500" />
          {item.label}
        </div>
      ),
      command: () => setFilters((f) => ({ ...f, priority: "HIGH" })),
    },
    {
      label: "Medium (5-7)",
      template: (item) => (
        <div className="flex items-center gap-2 p-2 text-amber-600 font-bold">
          <div className="size-2 rounded-full bg-amber-500" />
          {item.label}
        </div>
      ),
      command: () => setFilters((f) => ({ ...f, priority: "MEDIUM" })),
    },
    {
      label: "Low (1-4)",
      template: (item) => (
        <div className="flex items-center gap-2 p-2 text-emerald-600 font-bold">
          <div className="size-2 rounded-full bg-emerald-500" />
          {item.label}
        </div>
      ),
      command: () => setFilters((f) => ({ ...f, priority: "LOW" })),
    },
  ];

  useEffect(() => {
    const timer = setTimeout(() => {
      setDebouncedSearch(search);
    }, 400); // delay

    return () => clearTimeout(timer);
  }, [search]);

  useEffect(() => {
    setPage(1);
  }, [debouncedSearch, filters.status]);

  return (
    <div className="flex-1 space-y-6 p-10 bg-[#f6f6f8] dark:bg-[#101622] min-h-screen font-sans">
      {/* Page Heading */}
      <nav className="flex items-center gap-2 mb-6 text-sm font-medium text-slate-500">
        <NavLink
          to="/workflows"
          className="hover:text-blue-600 transition-colors"
        >
          Workflows
        </NavLink>
        <ChevronRight size={14} />
        <NavLink
          to={`/workflows/${workflowId}`}
          className="text-slate-900 dark:text-white hover:text-blue-600 transition-colors"
        >
          {workflowId}
        </NavLink>
        <ChevronRight size={14} />
        <span className="text-slate-900 dark:text-white">Approvals</span>
      </nav>
      <div className="flex flex-wrap justify-between items-end gap-3">
        <div className="flex flex-col gap-1">
          <h1 className="text-slate-900 dark:text-white text-4xl font-black leading-tight tracking-tight">
            Approvals
          </h1>
          <p className="text-slate-500 dark:text-slate-400 text-sm font-normal">
            Monitoring and governance of approvals generated by Enterprise
            Workflow #{workflowId}
          </p>
        </div>
        <div className="flex gap-3">
          <button className="flex items-center justify-center rounded-lg h-10 px-4 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-white text-sm font-bold hover:bg-slate-50 transition-colors">
            <ShieldCheck size={18} className="mr-2" />
            <span>View Approval Rules</span>
          </button>
          <button className="flex items-center justify-center rounded-lg h-10 px-4 bg-[#0f49bd] text-white text-sm font-bold hover:bg-blue-700 transition-colors shadow-lg shadow-blue-900/20">
            <Zap size={18} className="mr-2" />
            <span>Escalation Settings</span>
          </button>
        </div>
      </div>

      {/* KPI Section */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <KPICard
          label="Pending"
          value="142"
          trend="+12.5%"
          status="In Review"
          color="primary"
          isUp
        />
        <KPICard
          label="Approved"
          value="894"
          trend="-5.2%"
          status="Finalized"
          color="emerald"
          isUp={false}
        />
        <KPICard
          label="Rejected"
          value="23"
          trend="+2.1%"
          status="Terminated"
          color="rose"
          isUp
        />
        <KPICard
          label="Avg Approval Time"
          value="1.4 Days"
          trend="-10%"
          status="SLA Metric"
          color="amber"
          isUp={false}
        />
      </div>

      {/* Filter Bar */}

      <div className="">
        <div className="flex gap-3 py-3 justify-between flex-wrap items-center ">
          <div className=" relative h-12 w-full ">
            <Search
              className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"
              size={18}
            />
            <input
              className="w-full h-full pl-10 pr-4 rounded-lg border border-gray-300 dark:border-slate-700 bg-white dark:bg-[#1f2937] text-sm focus:ring-2 focus:ring-[#0f49bd] outline-none shadow-md "
              type="text"
              placeholder="Search by Approval ID"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
            />
            {search && (
              <button
                onClick={() => setSearch("")}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600"
              >
                <X size={14} />
              </button>
            )}
          </div>
          <div className="flex items-center gap-2">
            <Menu
              model={statusItems}
              popup
              ref={menuStatus}
              id="status_menu"
              className="cursor-pointer p-2 border-none shadow-2xl rounded-2xl bg-white dark:bg-gray-900 w-48"
              pt={{
                list: { className: "flex flex-col gap-1" },
                action: {
                  className:
                    "hover:bg-blue-100 dark:hover:bg-gray-800 rounded-lg transition-colors p-3",
                },
                label: {
                  className:
                    "text-sm font-bold text-gray-700 dark:text-gray-200",
                },
              }}
            />

            {/* Status Filter Button */}
            <FilterButton
              label="Status"
              value={filters.status}
              isActive={filters.status !== "All"}
              icon={<ChevronDown size={14} />}
              onClick={(e) => menuStatus.current.toggle(e)}
            />
            <Menu
              model={priorityItems}
              popup
              ref={menuPriority}
              className="cursor-pointer p-2 border-none shadow-2xl rounded-2xl bg-white dark:bg-gray-900 w-48"
              pt={{
                list: { className: "flex flex-col gap-1" },
                action: {
                  className:
                    "hover:bg-blue-100 dark:hover:bg-gray-800 rounded-lg transition-colors p-3",
                },
                label: {
                  className:
                    "text-sm font-bold text-gray-700 dark:text-gray-200",
                },
              }}
            />
            <FilterButton
              label="Priority"
              value={filters.priority}
              isActive={filters.priority !== "All"}
              icon={<ChevronDown size={14} />}
              onClick={(e) => menuPriority.current.toggle(e)}
            />

            {/* The Calendar Component */}
            {(filters.status !== "All" || filters.priority !== "All") && (
              <>
                <div className="h-6 w-px bg-gray-200 dark:bg-gray-700 mx-2"></div>
                <button
                  onClick={() =>
                    setFilters({
                      status: "All",
                      priority: "All",
                    })
                  }
                  className="text-[#135bec] text-xs font-black uppercase tracking-tight hover:text-blue-700 cursor-pointer transition-colors"
                >
                  Clear All
                </button>
              </>
            )}
          </div>
        </div>
      </div>

      {/* Main Table */}
      <div className="bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 overflow-hidden shadow-sm">
        <div className="overflow-x-auto">
          <DynamicTable
            tableData={approvalData}
            loading={loading}
            handleRowClick={(id) => handleRowClick(id)}
            first={(page - 1) * rows}
            rows={rows}
            tableHead={TableSchemas.approval}
          />
        </div>
        <div className="px-6 py-4 bg-slate-50 dark:bg-slate-800/50 border-t border-slate-200 dark:border-slate-800 flex items-center justify-between">
          <Paginator
            first={(page - 1) * rows}
            rows={rows}
            onPageChange={onPageChange}
            totalRecords={total}
          />
        </div>
      </div>
    </div>
  );
};

/* --- Sub-Components for Cleanliness --- */

const KPICard = ({ label, value, trend, status, color, isUp }) => {
  const colorMap = {
    primary: "bg-blue-500/10 text-blue-600",
    emerald: "bg-emerald-500/10 text-emerald-600",
    rose: "bg-rose-500/10 text-rose-500",
    amber: "bg-amber-500/10 text-amber-500",
  };

  return (
    <div className="flex flex-col gap-2 rounded-xl p-6 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm">
      <div className="flex justify-between items-start">
        <p className="text-slate-500 dark:text-slate-400 text-sm font-medium">
          {label}
        </p>
        <span
          className={`${colorMap[color]} text-[10px] font-bold px-2 py-0.5 rounded-full uppercase`}
        >
          {status}
        </span>
      </div>
      <p className="text-slate-900 dark:text-white text-4xl font-bold tracking-tight">
        {value}
      </p>
      <div
        className={`flex items-center gap-1 text-sm font-medium ${isUp ? "text-emerald-500" : "text-rose-500"}`}
      >
        {isUp ? <ArrowUpRight size={14} /> : <ArrowDownRight size={14} />}
        <span>{trend} vs last month</span>
      </div>
    </div>
  );
};

const UserCell = ({ name, img }) => (
  <div className="flex items-center gap-2">
    <div className="w-6 h-6 rounded-full bg-slate-200 dark:bg-slate-700 overflow-hidden">
      <img src={img} alt={name} className="w-full h-full object-cover" />
    </div>
    <span className="text-sm text-slate-700 dark:text-slate-300 whitespace-nowrap">
      {name}
    </span>
  </div>
);

const ActionBtn = ({ icon, title, color = "slate" }) => (
  <button
    className={`p-1.5 rounded transition-colors ${
      color === "rose"
        ? "hover:bg-rose-100 dark:hover:bg-rose-900/30 text-slate-400 hover:text-rose-600"
        : "hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-400 hover:text-[#0f49bd]"
    }`}
    title={title}
  >
    {icon}
  </button>
);

export default WorkflowApprovals;
